vim.keymap.set("n", "<C-k>ha", ":lua require(\"harpoon.mark\").add_file()<CR>")
vim.keymap.set("n", "<C-k>hh", ":lua require(\"harpoon.ui\").toggle_quick_menu()<CR>")
vim.keymap.set("n", "<C-k>hn", ":lua require(\"harpoon.ui\").nav_next()<CR>")
vim.keymap.set("n", "<C-k>hp", ":lua require(\"harpoon.ui\").nav_prev()<CR>")
vim.keymap.set("n", "<C-k>h1", ":lua require(\"harpoon.ui\").nav_file(1)<CR>")
vim.keymap.set("n", "<C-k>h2", ":lua require(\"harpoon.ui\").nav_file(2)<CR>")
vim.keymap.set("n", "<C-k>h3", ":lua require(\"harpoon.ui\").nav_file(3)<CR>")
vim.keymap.set("n", "<C-k>h4", ":lua require(\"harpoon.ui\").nav_file(4)<CR>")
vim.keymap.set("n", "<C-k>h5", ":lua require(\"harpoon.ui\").nav_file(5)<CR>")
vim.keymap.set("n", "<C-k>h6", ":lua require(\"harpoon.ui\").nav_file(6)<CR>")
vim.keymap.set("n", "<C-k>h7", ":lua require(\"harpoon.ui\").nav_file(7)<CR>")
vim.keymap.set("n", "<C-k>h8", ":lua require(\"harpoon.ui\").nav_file(8)<CR>")
vim.keymap.set("n", "<C-k>h9", ":lua require(\"harpoon.ui\").nav_file(9)<CR>")
vim.keymap.set("n", "<C-k>h0", ":lua require(\"harpoon.ui\").nav_file(0)<CR>")
vim.keymap.set("n", "<C-k>ht", ":Telescope harpoon marks theme=dropdown<CR>")
