vim.keymap.set("n", "<leader>ha", ":lua require(\"harpoon.mark\").add_file()<CR>")
vim.keymap.set("n", "<leader>hh", ":lua require(\"harpoon.ui\").toggle_quick_menu()<CR>")
vim.keymap.set("n", "<leader>hn", ":lua require(\"harpoon.ui\").nav_next()<CR>")
vim.keymap.set("n", "<leader>hp", ":lua require(\"harpoon.ui\").nav_prev()<CR>")
vim.keymap.set("n", "<leader>h1", ":lua require(\"harpoon.ui\").nav_file(1)<CR>")
vim.keymap.set("n", "<leader>h2", ":lua require(\"harpoon.ui\").nav_file(2)<CR>")
vim.keymap.set("n", "<leader>h3", ":lua require(\"harpoon.ui\").nav_file(3)<CR>")
vim.keymap.set("n", "<leader>h4", ":lua require(\"harpoon.ui\").nav_file(4)<CR>")
vim.keymap.set("n", "<leader>h5", ":lua require(\"harpoon.ui\").nav_file(5)<CR>")
vim.keymap.set("n", "<leader>h6", ":lua require(\"harpoon.ui\").nav_file(6)<CR>")
vim.keymap.set("n", "<leader>h7", ":lua require(\"harpoon.ui\").nav_file(7)<CR>")
vim.keymap.set("n", "<leader>h8", ":lua require(\"harpoon.ui\").nav_file(8)<CR>")
vim.keymap.set("n", "<leader>h9", ":lua require(\"harpoon.ui\").nav_file(9)<CR>")
vim.keymap.set("n", "<leader>h0", ":lua require(\"harpoon.ui\").nav_file(0)<CR>")
vim.keymap.set("n", "<leader>ht", ":Telescope harpoon marks<CR>")
